### ISSUE TITLE
好像缺了prnet.h和prnet.cpp文件

### ISSUE THREAD

**Issue by jiangzhongbo** [taylorlu/FaceConverter#1]
rt

**Comment by taylorlu** [comment]
Really? This project can running without other dependencies.

**Comment by jiangzhongbo** [comment]
在prnet目录里面好像没有prnet.h文件，但是ViewController.h里面引用了prnet.h
-------------------------
您好，我之前给您发了邮件，您请查收下。（知乎也发了私信）

**Comment by taylorlu** [comment]
I know what you need to do at first, you should click `prnet.mlmodel` in Xcode and generate `prnet.h` before you compile it.

**Comment by jiangzhongbo** [comment]
谢谢！是我不熟悉IOS的原因。

ps：
1.您有没有兴趣换一份工作，或者业余的时候做点感兴趣的外包。
2.我们公司拿了红衫不少钱并且965。
3.有兴趣的话回一下邮件或者知乎私信
